
export default function Gallery() {
    return (
        <div>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
            <h1>Gallery</h1>
        </div>
    )
}