
export default function Home() {
    return (
        <div>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            <h1>Dashboard</h1>
        </div>
    )
}